// GÉNÉRÉ par scripts/generate-feature-digest.mjs — snapshot périodique (PAS live, PAS à chaque build).
// But : donner à agents-triage.js un signal bon marché "ça ressemble à une feature déjà construite"
// sans accès repo live (impossible depuis un Worker) ni appel API externe (pas de nouveau secret).
// Régénérer manuellement (node scripts/generate-feature-digest.mjs) quand le digest semble périmé —
// un oubli dégrade juste la fraîcheur du signal, ne casse jamais le build (fichier committé).
// Dernière génération : 2026-07-21

export const ENDPOINTS_DIGEST = [
  "/api/admin-auth (admin-auth.js) — Vérifie le mot de passe admin côté serveur (jamais exposé dans le bundle JS).",
  "/api/agent-drafts (agent-drafts.js) — Système de brouillons générés par les agents IA, en attente d'approbation humaine",
  "/api/agent-lessons (agent-lessons.js) — Stockage des \"leçons apprises\" / mots-expressions interdits par les agents IA.",
  "/api/agent-memory (agent-memory.js) — CRUD pour les mémoires persistantes des agents IA",
  "/api/agents-actions (agents-actions.js) — CRUD pour les actions des 17 agents Amaryllis",
  "/api/agents-deliver (agents-deliver.js) — #5 BRAS EXÉCUTANT ÉLARGI : les agents produisent des LIVRABLES PRÊTS À L'EMPLOI",
  "/api/agents-eval (agents-eval.js) — #4 Harness d'évaluation : un LLM-juge note les sorties d'agents récentes",
  "/api/agents-orchestrate (agents-orchestrate.js) — #1 ORCHESTRATEUR (chef d'orchestre) : reçoit un OBJECTIF transverse, le décompose,",
  "/api/agents-run (agents-run.js) — Déclenche l'analyse autonome des agents via l'API Anthropic",
  "/api/agents-stats (agents-stats.js) — #7 Observabilité agents : un seul appel = vue d'ensemble pour piloter l'équipe IA.",
  "/api/agents-triage (agents-triage.js) — Triage hebdo AUTOMATIQUE du backlog des ~28 agents IA (agent_actions).",
  "/api/agents-triggers (agents-triggers.js) — #6 DÉCLENCHEURS RÉACTIFS (event-driven) : compare l'état courant à un état mémorisé",
  "/api/agents-verify (agents-verify.js) — #3 Vérification adversariale pour les agents à ENJEU (juridique, financier).",
  "/api/ai-ops (ai-ops.js) — AGENT AI-OPS : gère en continu les sources d'IA GRATUITES des agents Amaryllis.",
  "/api/ai-summary (ai-summary.js) — Proxy sécurisé vers l'API Anthropic — clé jamais exposée au navigateur",
  "/api/airbnb-test (airbnb-test.js) — Test READ-ONLY : authentification Airbnb + lecture des prix actuels",
  "/api/analytics (analytics.js) — Proxy vers Google Analytics Data API v1beta (GA4)",
  "/api/backlog-verify (backlog-verify.js) — I-11 — Vérificateur autonome du backlog agent_actions (\"la machine tourne seule\").",
  "/api/beds24-bookings (beds24-bookings.js) — Proxy sécurisé vers l'API Beds24 V2 — token jamais exposé au navigateur",
  "/api/beds24-create (beds24-create.js) — Crée une réservation Beds24 V2 directement via API (remplace l'iframe).",
  "/api/beds24-manage (beds24-manage.js) — Actions : find | confirm | cancel (publiques, tunnel voyageur) | restoreGuest (admin)",
  "/api/beds24-prices (beds24-prices.js) — Dérive les tarifs journaliers de Nogent (propId 158192) depuis les réservations Beds24.",
  "/api/beds24-rates (beds24-rates.js) — Récupère les tarifs journaliers Beds24 pour Nogent (propId=158192, roomId=348880)",
  "/api/beds24-refresh (beds24-refresh.js) — arch-009 : Rotation automatique du token Beds24 V2.",
  "/api/beds24-token-watch (beds24-token-watch.js) — web-009 : Surveillance quotidienne du token Beds24 V2",
  "/api/beds24-webhook (beds24-webhook.js) — Reçoit les notifications Beds24 en temps réel → transmet à Apps Script",
  "/api/bug-triage (bug-triage.js) — Agent de triage hebdo des bugs. Lit les bugs \"new\" récents (client_errors),",
  "/api/cache-purge (cache-purge.js) — arch-011 (Architecte Réseau, BASSE) : /api/analytics passe à un TTL CDN de 1min",
  "/api/cancel-booking (cancel-booking.js) — 🔒 Admin UNIQUEMENT : annule une réservation directe (Stripe LIVE, argent réel).",
  "/api/caution-checkout (caution-checkout.js) — Crée une Stripe Checkout Session en pré-autorisation (capture_method: manual)",
  "/api/caution-cron (caution-cron.js)",
  "/api/charge-balance (charge-balance.js) — Cron quotidien : débite off-session les soldes dus (paiement en 2 fois).",
  "/api/client-errors (client-errors.js) — Inbox auto-hébergée des bugs : erreurs JS captées en prod (site + admin)",
  "/api/code-review (code-review.js) — Revue de code LLM ciblée sur un DIFF (pas tout le code) : signale les bugs",
  "/api/complement-checkout (complement-checkout.js) — Crée une Stripe Checkout Session de PAIEMENT (capture immédiate) pour un COMPLÉMENT de prix",
  "/api/concierge (concierge.js) — I-10 — Concierge IA qui AGIT (pas qui répond).",
  "/api/contacts-alert (contacts-alert.js) — crm-007 : alerte ntfy pour les leads > 24h sans réponse.",
  "/api/contacts-purge (contacts-purge.js) — jur-008 : RGPD — purge des contacts de plus de 2 ans (durée légale maximale).",
  "/api/create-deposit-intent (create-deposit-intent.js) — Creates a PaymentIntent with capture_method: \"manual\" (pre-authorization)",
  "/api/create-payment-intent (create-payment-intent.js) — Enregistre un \"panier\" en D1 dès la création du PaymentIntent.",
  "/api/create-payment-link (create-payment-link.js) — ebiz-005 : Crée un Stripe Payment Link pour devis WhatsApp",
  "/api/delegation-stats (delegation-stats.js) — I-09 — Runbook de délégation auto-mesuré.",
  "/api/devis-solde-cron (devis-solde-cron.js) — Cron quotidien (cron-job.org) : gère le SOLDE des devis payés en 2 fois.",
  "/api/docs-refresh (docs-refresh.js)",
  "/api/editorial-calendar (editorial-calendar.js) — Planning éditorial Facebook + Instagram pour Amaryllis Locations.",
  "/api/editorial-gate (editorial-gate.js) — Gate de qualité d'AUTO-PUBLICATION réseaux. Remplace le clic « Approuver » humain :",
  "/api/editorial-photos (editorial-photos.js) — Whitelist des photos AUTORISÉES à la publication réseaux (les « plus belles »,",
  "/api/editorial-videos (editorial-videos.js) — Whitelist des vidéos AUTORISÉES pour la génération de Reels (sélectionnées",
  "/api/email-templates-admin (email-templates-admin.js) — Éditeur admin des paragraphes ÉDITABLES (texte simple) des 4 templates email",
  "/api/fetch-ical (fetch-ical.js) — Server-side proxy to bypass CORS for Booking.com / Airbnb iCal URLs",
  "/api/geo (geo.js) — Retourne le pays et la ville du visiteur via les headers Cloudflare.",
  "/api/get-availability (get-availability.js) — env vars accessed via context.env (set in CF Pages dashboard)",
  "/api/get-config (get-config.js) — Retourne la configuration admin : Apps Script URL + URLs iCal Airbnb.",
  "/api/guide-write (guide-write.js) — Auto-rédaction des guides voyageurs : l'IA réécrit UNIQUEMENT la prose d'accueil",
  "/api/health-check (health-check.js) — web-006 : retourne le statut des services critiques (D1, Beds24, Resend)",
  "/api/health (health.js) — État de santé du système Amaryllis Locations.",
  "/api/llm-generate (llm-generate.js) — Proxy générique vers callLLM (cascade multi-provider Groq/Cloudflare/Mistral/Cerebras)",
  "/api/llm-ping (llm-ping.js) — Health-check des fournisseurs LLM (Groq / Cloudflare AI / Mistral / Cerebras).",
  "/api/manage-deposit (manage-deposit.js) — action: \"capture\" | \"cancel\" | \"list\" | \"history\"",
  "/api/memory-distill (memory-distill.js) — Agent-mémoire (B2) : distille l'expérience du réseau (notes qualité llm_evals 7j +",
  "/api/occupancy-stats (occupancy-stats.js) — Occupation réelle 30 jours glissants, un chiffre par bien actif.",
  "/api/ops-sla-report (ops-sla-report.js) — Rapport mensuel SLA Exploitation (maintenance + stock) — log-036.",
  "/api/orchestrator (orchestrator.js) — Orchestrateur multi-agents : utilise claude-sonnet pour coordonner les 28 agents",
  "/api/ota-cost (ota-cost.js) — I-04 — Le vrai coût des OTA. Produit les FAITS (réels), le front applique les hypothèses.",
  "/api/pnl-sejour (pnl-sejour.js) — I-03 — P&L par séjour (pas CA par séjour). Décompose chaque réservation en coûts variables",
  "/api/prestataires (prestataires.js) — I-10 (prérequis) — Carnet de prestataires en D1.",
  "/api/qa-run (qa-run.js) — Trigger manuel d'une session QA.",
  "/api/rag-ingest (rag-ingest.js) — #2 RAG — alimente l'index vectoriel avec les VRAIES données : faits biens,",
  "/api/rag-search (rag-search.js) — #2 RAG — test/démo du retrieval : renvoie les passages les plus proches.",
  "/api/rm-dashboard (rm-dashboard.js) — Main dashboard data for the Revenue Manager module",
  "/api/rm-init (rm-init.js) — Initializes the Revenue Manager database (creates tables + seeds data)",
  "/api/rm-overrides (rm-overrides.js) — Manual price/min_stay/block overrides for specific dates",
  "/api/rm-price-digest (rm-price-digest.js) — Digest hebdo RM : parmi les 2500+ recommandations stockées (~14 mois glissants ×",
  "/api/rm-properties (rm-properties.js) — Property settings: list, get, update",
  "/api/send-guest-email (send-guest-email.js) — crm-010/016 — Envoi générique d'un email voyageur depuis un template HTML.",
  "/api/send-j1-acces (send-j1-acces.js) — Cron J-1 : envoie le code d'accès réel aux voyageurs arrivant demain.",
  "/api/send-menage-alert (send-menage-alert.js) — log-005 : Alerte automatique prestataire ménage J-2 avant arrivée",
  "/api/send-poststay (send-poststay.js) — crm-006 / growth-005 : séquence post-séjour à 2 touches MAXIMUM (demande Vincent",
  "/api/send-pre-depart (send-pre-depart.js) — Cron J-1 checkout : email la veille du départ — heure de départ, late check-out",
  "/api/send-prearrivee (send-prearrivee.js) — crm — Email pré-arrivée J-3 pour les RÉSERVATIONS DIRECTES uniquement.",
  "/api/send-prix-alert (send-prix-alert.js) — Envoie un email + push ntfy quand des prix sont sous le seuil minimum",
  "/api/send-prix-recap (send-prix-recap.js) — Envoie un récap email hebdomadaire des prix + liens Airbnb via Resend",
  "/api/send-relance-panier (send-relance-panier.js) — crm-016 — Relance panier abandonné pour les RÉSERVATIONS DIRECTES.",
  "/api/send-vacancy-alert (send-vacancy-alert.js) — rev-007 : Alerte vacance locative J+14 à J+30",
  "/api/send-veille-recap (send-veille-recap.js) — Rapport hebdo de veille concurrentielle (veille-003) : médian/p25/p75 marché par bien",
  "/api/send-verif-arrivee (send-verif-arrivee.js) — Cron J+1 arrivée : email court \"tout se passe bien ?\" le lendemain du check-in.",
  "/api/service-checkout (service-checkout.js) — Achat d'un SERVICE additionnel par le voyageur (depuis /services/<bien> ou le QR de l'écran TV).",
  "/api/sheets-proxy (sheets-proxy.js) — Proxy serveur → Apps Script pour éviter les CORS sur les gros payloads",
  "/api/shorten (shorten.js) — Liens courts pour les devis : villamaryllis.com/r/{code}",
  "/api/sign-contract (sign-contract.js) — Signature électronique « maison » du contrat de location : on stocke la",
  "/api/site-config (site-config.js) — Proxy bidirectionnel vers Google Apps Script (PropertiesService)",
  "/api/social-draft (social-draft.js) — Reçoit un texte libre (un post de groupe Facebook capté par la veille locale group-watch.mjs)",
  "/api/social-poll (social-poll.js) — Détecteur de leads SANS webhook (marche en mode développement, AUCUN App Review requis) :",
  "/api/social-webhook (social-webhook.js) — Bot social Amaryllis : répond AUTOMATIQUEMENT aux commentaires (Facebook Page + pubs, Instagram)",
  "/api/sync-health (sync-health.js) — Agrège la santé du pipeline de synchro résas (4 canaux) pour l'onglet admin",
  "/api/tv-context (tv-context.js) — Renvoie le contexte de séjour EN COURS pour l'écran d'accueil TV : { guest?, du?, au? }.",
  "/api/veille-zone-scan (veille-zone-scan.js) — veille-005 : détecte les NOUVEAUX listings apparus dans la zone (diff snapshot",
  "/api/voyageur-feedback (voyageur-feedback.js) — voyageur-001 : extraction + stockage des avis Airbnb des biens en D1.",
  "/api/weather (weather.js) — Proxy sécurisé vers OpenWeatherMap — clé jamais exposée au navigateur",
  "/api/whatsapp-conversations (whatsapp-conversations.js) — Lit la table whatsapp_conversations depuis D1 (revenue_manager).",
  "/api/whatsapp (whatsapp.js) — Bot WhatsApp Business (Meta Cloud API) pour les voyageurs Amaryllis."
];

export const ADMIN_TABS_DIGEST = [
  "AdBudgetTab",
  "AdminChatTab",
  "AnalyticsTab",
  "ApprobationsTab",
  "ArticlesTab",
  "AvisTab",
  "Beds24Admin",
  "BugsTab",
  "CalendrierTarifs",
  "Cautions",
  "Charges",
  "Cockpit",
  "ConversionTab",
  "CoutOtaTab",
  "CpaCanalTab",
  "CrmTab",
  "CroissanceTab",
  "DevStatusTab",
  "DevisEditor",
  "EditorialCalendarTab",
  "EditorialPhotosTab",
  "EditorialVideosTab",
  "FunnelTab",
  "GuestContactsTab",
  "Historique",
  "InterventionsTab",
  "InventaireTab",
  "LeadsTab",
  "LingeTab",
  "LivretQR",
  "MaintenanceTab",
  "MenageTab",
  "MessageTemplates",
  "MessagerieTab",
  "MinNightsConfig",
  "NetRevParTab",
  "NewsletterTab",
  "OrchestratorTab",
  "Pilotage",
  "Planning",
  "PnlSejourTab",
  "Prestataires",
  "Previsionnel",
  "ProjetsCerveauTab",
  "ReclamationsTab",
  "ReelsTab",
  "SEOAuditTab",
  "ServiceOrdersTab",
  "SocialTab",
  "StockTrackerTab",
  "StripeReconcileTab",
  "SyncHealthTab",
  "Tarifs",
  "Travaux",
  "WhatsAppTab"
];
